apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: ghcr.io/justanotherjavaprogrammer/imagenetwork-frontend:latest
          name: imagenetwork-frontend
          ports:
            - containerPort: 80
      imagePullSecrets:
      - name: dockerconfigjson-github-com
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-frontend-host
spec:
  rules:
  - host: "lukas.dev.local"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: frontend-service
            port:
              number: 80